set-option -g allow-rename off
set-window-option -g automatic-rename off

set -gq allow-passthrough

set -g mouse on
set -g history-limit 50000
set -g default-terminal "tmux-256color"
set -as terminal-features ',xterm-256color:RGB'

bind -T root WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "copy-mode -e"
bind -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X scroll-down

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set-option -g status-style bg=colour235,fg=colour136,default # bg=base02, fg=yellow
set-window-option -g window-status-style fg=colour244,bg=default,dim # fg=base0
# active window title colors
set-window-option -g window-status-current-style fg=colour166,bg=default,bright # fg=orange
set -s escape-time 50

# Activity monitoring
setw -g monitor-activity on
set -g visual-activity on


# pane border
set-option -g pane-border-style fg=colour235 #fg=base02
set-option -g pane-active-border-style fg=colour240 #fg=base01

# message text
set-option -g message-style bg=colour235,fg=colour166 # bg=base02, fg=orange

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange
# clock
set-window-option -g clock-mode-colour green #green

set -g window-status-format '#I:#W#F'

# Move status bar to top
set -g status-position top

# Left align window list
set -g status-justify left

# Window appearance
set -g window-status-format " #[fg=#666666] #I:#W "
set -g window-status-current-format " #[fg=#00ff00,bold] #I:#W "

# Make tabs more distinct
set -g window-status-separator ""

# Optional: shorten session info
set -g status-left "#S "
set -g status-right "%H:%M"
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."
bind-key v split-window -h
bind-key b split-window


set -g prefix `
unbind C-b
bind ` send-prefix

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# Rose Pine Main

set -g status-position top
set -g status-style "bg=#191724,fg=#e0def4"

set -g status-left-length 40
set -g status-right-length 80

set -g status-left "#[fg=#c4a7e7,bold] #S "

set -g status-right "#[fg=#f6c177] %a %b %d #[fg=#9ccfd8]| #[fg=#ebbcba]%I:%M %p "

set -g window-status-format "#[fg=#6e6a86] #I:#W "
set -g window-status-current-format "#[fg=#191724,bg=#c4a7e7,bold] #I:#W "

set -g pane-border-style "fg=#403d52"
set -g pane-active-border-style "fg=#c4a7e7"

set -g message-style "bg=#26233a,fg=#e0def4"
set -g mode-style "bg=#31748f,fg=#e0def4"
